flatbuffers/Enum.fbs
Reduce enum datatype sizes from int16 to int8.
=> feat: reduce enum datatype sizes

.github/workflows/ci-build.yml, build.sh, flatbuffers/Enum.fbs, flatbuffers/FeedRequest.fbs, flatbuffers/FeedRequestAck.fbs, flatbuffers/FeedRequestReject.fbs, flatbuffers/MDSnapshotL2.fbs, flatbuffers/Message.fbs, flatbuffers/PublicTrade.fbs, flatbuffers/SessionStatus.fbs
Add a build script for handling language-specific namespaces and code-generation options.
=> feat: language-specific namespace

CODEOWNERS, build.sh
Typescript build needs additional options to generate usable code.
Adding csharp build.
=> chore: adding csharp and typescript builds

.github/workflows/ci-build.yml, .github/workflows/master-build.yml, build.sh, flatbuffers/FeedRequestAccept.fbs, flatbuffers/Message.fbs
The "Accept" suffix is more consistent as a naming convention.
=> chore: rename FeedRequestAck to FeedRequestAccept

.github/workflows/npm.yml, .gitignore, package-lock.json, package.json, tsconfig.json
A package will be built and published to npm.
=> chore: publishing npm package on tagged builds

build.sh, flatbuffers/Enum.fbs, flatbuffers/FeedRequest.fbs, flatbuffers/FeedRequestAccept.fbs, flatbuffers/FeedRequestReject.fbs, flatbuffers/MDSnapshotL2.fbs, flatbuffers/Message.fbs, flatbuffers/PublicTrade.fbs, flatbuffers/SessionStatus.fbs
Modify the build script, so that it can generate code with language-specific namespaces for all languages.
=> feat: language-specific namespaces

build.sh
Update namespaces for C++ and Python, so that the generated code is consistent with existing projects.
=> feat: update C++ and Python namespaces

.github/workflows/pypi.yml, python/setup.py
Make reactive as namespace in platform-papi python package.
DEV-2087
=> DEV-2087: make reactive as namespace for python package

.github/workflows/maven.yml, .gitignore, pom.xml
Changes:
- add github action to build and publish jar to maven on tag
- add pom.xml with plugins for deploying to maven
=> feat: publish papi jar to maven

.github/workflows/maven.yml, .github/workflows/npm.yml, .github/workflows/pypi.yml, README.md, pom.xml
README.md update and general cleanups.
DEV-2053
=> chore: update the readme file

.github/workflows/maven.yml, pom.xml
Infer the release version from the GitHub ref and inject into pom.xml.
DEV-2096
=> DEV-2096: set Maven version from GitHub ref

flatbuffers/LiquidationOrder.fbs, flatbuffers/Message.fbs
Add Flatbuffers liquidation table.
DEV-2199
=> DEV-2199: add liquidation table

flatbuffers/LiquidationOrder.fbs
=> DEV-2221: add exec_venue into LiquidationOrder

.github/workflows/ci.yml, .github/workflows/master-build.yml, .github/workflows/npm.yml, .gitignore, README.md, build.sh, js/CONTRIBUTING.md, js/LICENSE, js/README.md, js/package-lock.json, js/package.json, js/tsconfig.json
=> feat: platform renamed to switchboard

.github/workflows/ci.yml, .github/workflows/master-build.yml, build.sh
Latest version doesn't create valid typescript.
=> build(github): fixing version of flatc to correctly make typescript

openapi/openapi.json
=> feat: updating openapi spec to v1

flatbuffers/ExecutionReport.fbs, flatbuffers/NewOrderSingle.fbs, openapi/openapi.json
- ccy added to NOS and ER.
- Updating openapi
=> Add ccy & update openapi

flatbuffers/Enum.fbs, flatbuffers/MarketDataRequest.fbs, flatbuffers/MarketDataSnapshot.fbs, flatbuffers/NewOrderSingle.fbs, flatbuffers/OrderCancelReject.fbs, flatbuffers/OrderCancelRequest.fbs, flatbuffers/OrderReplaceRequest.fbs
Defaults to SpotFwd if not specified.
=> feat(flatbuffers): adding security type

flatbuffers/MarketDataSnapshot.fbs
adding support for forward points
SD-2008
=> feat: add forward points to MD snapshot

flatbuffers/MarketDataSnapshot.fbs
We need to publish a blank book.
=> fix(flatbuffers): removing required attribute from bid/offer

flatbuffers/MarketDataSnapshot.fbs
Added reserved field to MDEntry struct.
Remove req_id field.
=> feat(flatbuffers): adding reserved field, removed req_id

flatbuffers/Enum.fbs
We plan to rename SpotFwd to Spot in a future change
SDB-3599
=> feat(flatbuffers): add forward instrument type

flatbuffers/ExecutionReport.fbs, flatbuffers/NewOrderSingle.fbs
New field on NOS and ExecutionReport.
SD-2350
=> feat(flatbuffers): adding venue_filter

flatbuffers/Enum.fbs, flatbuffers/ExecutionReport.fbs, flatbuffers/MarketDataAcknowledgement.fbs, flatbuffers/MarketDataRequest.fbs, flatbuffers/MarketDataSnapshot.fbs, flatbuffers/Message.fbs, flatbuffers/NewOrderSingle.fbs, flatbuffers/OrderCancelReject.fbs, flatbuffers/OrderCancelRequest.fbs, flatbuffers/Quote.fbs, flatbuffers/QuoteAcknowledgement.fbs, flatbuffers/QuoteCancel.fbs, flatbuffers/QuoteRequest.fbs
Initial proposal for RFQ.
SD-2462
=> feat(flatbuffers): RFQ/S messages

flatbuffers/Quote.fbs
We'll now send 1 messages per venue instead of many venues.
=> fix(flatbuffers): reducing nesting in quote messages

flatbuffers/QuoteCancel.fbs
Required to generate key and remove from account index
=> fix(flatbuffers): add account to quote cancel message

flatbuffers/QuoteRequest.fbs
=> feat(flatbuffers): add expiry_time to quote request

flatbuffers/QuoteRequest.fbs
=> fix(flatbuffers): change RFQ expiry field to int

flatbuffers/ExecutionReport.fbs, flatbuffers/NewOrderSingle.fbs, flatbuffers/QuoteRequest.fbs
Still binary compatabile so no breaking changes.
=> fix(flatbuffers): venue_filter has been renamed to exec_venues

flatbuffers/ExecutionReport.fbs, flatbuffers/NewOrderSingle.fbs, flatbuffers/Quote.fbs
=> feat(flatbuffers): adding support for swaps

flatbuffers/Quote.fbs
=> feat(quote): add settlement_date to quote fb

flatbuffers/Heartbeat.fbs, flatbuffers/Market.fbs, flatbuffers/Metric.fbs, flatbuffers/QuoteCancel.fbs, flatbuffers/StrategyParameter.fbs, flatbuffers/TestRequest.fbs
Allows optional metrics to be sent for monitoring purposes.
=> feat(flatbuffers): adding metrics to heartbeat and test request

flatbuffers/MarketDataRequestReject.fbs, flatbuffers/QuoteRequestReject.fbs
new QuoteRequestReject and MarketDataRequestReject messages
SD-3345
=> feat(flatbuffers): new request reject messages

flatbuffers/ExecutionReport.fbs
Added missing swap fields to exec report flatbuffer
SD-3758
=> feat(flatbuffers): added swaps fields to exec report fb

flatbuffers/ExecutionReport.fbs, flatbuffers/MarketDataSnapshot.fbs, flatbuffers/Quote.fbs
We need to support mid prices on Quotes, MarketDataSnapshots and Execution reports
SD-4383
=> feat(flatbuffers): add Dodd-Frank mid price properties

flatbuffers/Enum.fbs, flatbuffers/ExecutionReport.fbs, flatbuffers/OrderReplaceRequest.fbs
=> feat(flatbuffers): add execution instruction to OrderReplaceRequest

flatbuffers/Enum.fbs
=> feat(flatbuffers): add Stop order type
